### ISSUE TITLE
EPIC: 3.x roadmap

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/behat-steps#134]
- [x] Add the step definition creation rules to the README.md (see the comment below).
- [x] Reconcile all step definitions format to follow industry best practices (need a link here)
- [x] Reconcile traits with the latest version of Drupal Extension to remove duplicating functionality
- [x] Prepend Drupal trait names with `Drupal` and add `drupal` prefix to all functions
- [x] Add Drupal 11 fixture and CI build

- #279
- #280
- #281
- #282
- #283
- #284
- #285
- #286
- #287
- #288
- #289
- #290
- #291
- #292
- #293
- #294
- #295
- #296
- #297
- #298
- #299
- #300
- #301
- #302
- #303
- #319
- #367
- #368

**Comment by AlexSkrypnyk** [comment]
Steps reconciliation spreadsheet:  
https://docs.google.com/spreadsheets/d/11zTWgbRdTIMaXBkwli9qiZINqxxBDuKq9BhpT9iPBok/edit?usp=sharing

**Comment by AlexSkrypnyk** [comment]
Release prep checklist

- [ ] One more pass for the language in the `MIGRATION.md`
- [ ] Review `README.md`
- [ ] Update variables to use snake_case format
- [ ] Re-assess if any traits can be merged
- [ ] Re-assess if any Drupal-specific traits can be namespaced
- [ ] Re-assess dependencies to make sure that consumer projects can use non-Drupal steps without downloading DrupalExtension

**Comment by AlexSkrypnyk** [comment]
3.x was released!
